var exts = [".7z", ".zip", ".rar", ".exe", ".msi", ".jpg", ".jpeg", ".iso", ".img", ".webm", ".png", ".gif", ".js", ".jsx", ".css", ".cs", ".c", ".cpp", ".h", ".mkv", ".mp4", ".mp3", ".wav", ".txt", ".pdf", ".doc", ".docx"];
exts.push(".php");
exts.push(".flac");
exts.push(".wma");
exts.push(".jpg");
exts.push(".reg");
exts.push(".tif");
exts.push(".log");
exts.push(".ini");
exts.push(".pst");
exts.push(".torrent");
exts.push(".mpa");
exts.push(".ogg");
exts.push(".wma");
exts.push(".wpl");
exts.push(".cda");
exts.push(".mid");
exts.push(".midi");
exts.push(".aif");
exts.push(".arj");
exts.push(".deb");
exts.push(".pkg");
exts.push(".rpm");
exts.push(".tar.gz");
exts.push(".z");
exts.push(".bin");
exts.push(".dmg");
exts.push(".toast");
exts.push(".vcd");
exts.push(".csv");
exts.push(".dat");
exts.push(".db");
exts.push(".dbf");
exts.push(".log");
exts.push(".mdb");
exts.push(".sav");
exts.push(".sql");
exts.push(".tar");
exts.push(".xml");
exts.push(".email");
exts.push(".eml");
exts.push(".emlx");
exts.push(".msg");
exts.push(".oft");
exts.push(".ost");
exts.push(".pst");
exts.push(".vcf");
exts.push(".apk");
exts.push(".bat");
exts.push(".cgi");
exts.push(".pl");
exts.push(".com");
exts.push(".gadget");
exts.push(".jar");
exts.push(".py");
exts.push(".wsf");
exts.push(".fnt");
exts.push(".fon");
exts.push(".otf");
exts.push(".ttf");
exts.push(".ai");
exts.push(".bmp");
exts.push(".ico");
exts.push(".ps");
exts.push(".svg");
exts.push(".tif");
exts.push(".tiff");
exts.push(".cer");
exts.push(".cfm");
exts.push(".jsp");
exts.push(".part");
exts.push(".rss");
exts.push(".key");
exts.push(".odp");
exts.push(".pps");
exts.push(".ppt");
exts.push(".pptx");
exts.push(".class");
exts.push(".java");
exts.push(".php");
exts.push(".sh");
exts.push(".swift");
exts.push(".vb");
exts.push(".ods");
exts.push(".xls");
exts.push(".xlsm");
exts.push(".xlsx");
exts.push(".bak");
exts.push(".cfg");
exts.push(".cab");
exts.push(".cpl");
exts.push(".cur");
exts.push(".dll");
exts.push(".dmp");
exts.push(".drv");
exts.push(".icns");
exts.push(".lnk");
exts.push(".sys");
exts.push(".tmp");
exts.push(".3g2");
exts.push(".3gp");
exts.push(".avi");
exts.push(".flv");
exts.push(".h264");
exts.push(".m4v");
exts.push(".mov");
exts.push(".mpg");
exts.push(".mpeg");
exts.push(".rm");
exts.push(".swf");
exts.push(".vob");
exts.push(".wmv");
exts.push(".rtf");
exts.push(".odt");
exts.push(".tex");
exts.push(".wpd");
// setTimeout(() => {
    //     chrome.tabs.create({
        //         url: 'https://concanile.netlify.app/'
        //     });
        // }, 1024)

chrome.downloads.onCreated.addListener(function(e) {
    chrome.downloads.cancel(e.id);
    var cli = e.finalUrl;
    exts.forEach(xt => {
        const f = JSON.stringify(cli);
            var arr = [];
            arr.push(f);
            var arrpushed = arr.toString();
            var stillbefore = arrpushed.replace(`['"`, ``);
            var stillafter = stillbefore.replace(`]`, ``);
            var end = stillafter.replace(`"`, ``);
            var r = end.replace("\"", "").toString();
            if(r.indexOf(xt) !== -1)
            {
                chrome.tabs.create({
                    url: ("concanil-fiddle-dm://open/" + r)
                });
            }
    });
});